"""empty message

Revision ID: 12de2bd11953
Revises: 2a00f4469ef3
Create Date: 2017-02-27 12:23:08.038426

"""

# revision identifiers, used by Alembic.
revision = '12de2bd11953'
down_revision = '2a00f4469ef3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
