"""empty message

Revision ID: 28ab9a07f1d6
Revises: 2ba2f91a5bcf
Create Date: 2017-02-24 02:37:13.402761

"""

# revision identifiers, used by Alembic.
revision = '28ab9a07f1d6'
down_revision = '2ba2f91a5bcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
