"""empty message

Revision ID: 2a00f4469ef3
Revises: 438f33946fcd
Create Date: 2017-02-27 12:16:15.157176

"""

# revision identifiers, used by Alembic.
revision = '2a00f4469ef3'
down_revision = '438f33946fcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
