"""empty message

Revision ID: 30cd6b0240e2
Revises: 12de2bd11953
Create Date: 2017-02-27 12:41:40.978388

"""

# revision identifiers, used by Alembic.
revision = '30cd6b0240e2'
down_revision = '12de2bd11953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
