"""empty message

Revision ID: 438f33946fcd
Revises: 28ab9a07f1d6
Create Date: 2017-02-27 12:13:42.967331

"""

# revision identifiers, used by Alembic.
revision = '438f33946fcd'
down_revision = '28ab9a07f1d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
