"""empty message

Revision ID: 51facfec70f9
Revises: 30cd6b0240e2
Create Date: 2017-02-27 12:45:58.581551

"""

# revision identifiers, used by Alembic.
revision = '51facfec70f9'
down_revision = '30cd6b0240e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
